  build-linux:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make wget

    - name: Build SQLite
      run: |
        wget https://www.sqlite.org/2025/sqlite-autoconf-3450000.tar.gz
        tar xzf sqlite-autoconf-3450000.tar.gz
        cd sqlite-autoconf-3450000
        ./configure --enable-load-extension --prefix=$HOME/sqlite
        make
        make install

    - name: Patch go-sqlite3
      run: |
        go mod edit -replace github.com/mattn/go-sqlite3=./go-sqlite3
        git clone https://github.com/mattn/go-sqlite3.git
        cd go-sqlite3
        # Apply minimal patch: enable extension loading
        sed -i 's|#cgo CFLAGS:|#cgo CFLAGS: -DSQLITE_ENABLE_LOAD_EXTENSION=1|' sqlite3.go

    - name: Build sqlite-server
      run: |
        export CGO_CFLAGS="-I$HOME/sqlite/include"
        export CGO_LDFLAGS="-L$HOME/sqlite/lib"
        GOOS=linux GOARCH=amd64 go build -v -o sqlite-server-linux

    - name: Download Steampipe GitHub extension
      run: |
        wget https://downloads.steampipe.io/plugins/turbot/steampipe-sqlite-github/latest/steampipe_sqlite_github_linux_amd64.so
        mv steampipe_sqlite_github_linux_amd64.so steampipe_sqlite_github.so

    - name: Create tar.gz archive
      run: |
        tar -czf sqlite-server-linux.tar.gz sqlite-server-linux steampipe_sqlite_github.so

    - name: Upload Linux release asset
      uses: softprops/action-gh-release@v2
      with:
        files: sqlite-server-linux.tar.gz
        tag_name: ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
