name: Build Binaries

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Linux binary
      run: |
        GOOS=linux GOARCH=amd64 go build -v -o sqlite-server-linux

    - name: Create tar.gz archive
      run: |
        tar -czf sqlite-server-linux.tar.gz sqlite-server-linux

    - name: Upload Linux release asset
      uses: softprops/action-gh-release@v2
      with:
        files: sqlite-server-linux.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest
    needs: build-linux
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build macOS ARM64 binary
      run: |
        GOOS=darwin GOARCH=arm64 go build -v -o sqlite-server-mac-arm

    - name: Create tar.gz archive
      run: |
        tar -czf sqlite-server-mac-arm.tar.gz sqlite-server-mac-arm

    - name: Upload macOS release asset
      uses: softprops/action-gh-release@v2
      with:
        files: sqlite-server-mac-arm.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
