name: Build Binaries

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary: sqlite-server-linux
          - os: macos-latest
            binary: sqlite-server-macos
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        GOOS=${{ runner.os == 'Linux' && 'linux' || 'darwin' }} \
        GOARCH=amd64 \
        go build -v -o ${{ matrix.binary }}

    - name: Commit and push binary
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add ${{ matrix.binary }}
        git commit -m "Update ${{ matrix.binary }} binary" || echo "No changes to commit"
        git push