name: Debug Simple

on:
  workflow_dispatch:
    inputs:
      level:
        description: "Debug level"
        default: "1"
        required: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Basic check
        run: |
          echo "Basic debugging test"
          ls -la
