name: SQLite Extension Diagnostic

on:
  workflow_dispatch:

jobs:
  diagnose-sqlite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Run diagnostic script
        run: |
          chmod +x ./diagnostic.sh
          ./diagnostic.sh